# Generated by Django 2.1.1 on 2018-09-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('current_holder', models.IntegerField()),
                ('raised_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='clientid',
            new_name='client_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='owner',
        ),
        migrations.AddField(
            model_name='employee',
            name='client',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
