# Generated by Django 2.0.6 on 2018-10-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='current_holder_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='client',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='client_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='by',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
