# Generated by Django 2.0.6 on 2018-10-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20181020_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='client',
            new_name='client_name',
        ),
    ]
