# Generated by Django 2.0.6 on 2018-10-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20181020_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='current_holder_email',
            field=models.EmailField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=70, null=True),
        ),
    ]
