# Generated by Django 2.0.6 on 2018-10-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20181020_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
