# Generated by Django 2.0.6 on 2018-10-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_ticket_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
