# Generated by Django 2.0.6 on 2018-10-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(default=0),
        ),
    ]
