# Generated by Django 2.0.6 on 2018-10-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_employee_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.IntegerField(default=0),
        ),
    ]
