# Generated by Django 2.0.6 on 2018-10-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_ticket_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.IntegerField(default=0),
        ),
    ]
